### ISSUE TITLE
Evaluation data split?

### ISSUE THREAD

**Issue by ZhengdiYu** [zc-alexfan/digit-interacting#2]
Hi,

Thanks for your great work, I just want to confirm that what data split you are using in table 1 and table 2 separately, because they have different results. Your MPJPE is  16.55 in table 2 but  14.27 in table 1

**Comment by zc-alexfan** [comment]
It is the same split. 

In the training procedure paragraph, we said that we train on fewer epochs for ablations to speed things up.
