### ISSUE TITLE
Interhand dataset version?

### ISSUE THREAD

**Issue by adwardlee** [zc-alexfan/digit-interacting#7]
Hi, @zc-alexfan,

Thank you for releasing the great work. I am wondering the algorithm is conducted on interhand dataset v0.0 or v1.0? Thanks.

**Comment by zc-alexfan** [comment]
Hi, sorry for the delay. Our paper mentions "We use the final release of InterHand2.6M[37] for comparison with the state-of-the-art methods in the main paper and include the results of the initial release of [37] in Sup. Mat"
