### ISSUE TITLE
Can the project recognize gestures in real-time

### ISSUE THREAD

**Issue by jiangfeng999** [zc-alexfan/digit-interacting#8]
As mentioned in the question, we look forward to answering

**Comment by zc-alexfan** [comment]
thanks for your interest in our work. 

The project was 2 years ago, so I don't remember the details. However, in our paper, we wrote that "The baseline, our method, and [37] run at 26, 24, and 96 FPS on a Titan RTX". So I think it can be run on real time. 

However, the project is to perform 3D hand pose estimation, not gesture recognition. Further, it is trained on InterHand2.6M which has a dark background. So I think you need to perform hand segmentation first before feeding into the network.

**Comment by jiangfeng999** [comment]
Thank you very much for your reply and have a nice life!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zc-alexfan/digit-interacting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zc-alexfan/digit-interacting] Can the project recognize gestures in real-time (Issue #8)





 
thanks for your interest in our work.
 
The project was 2 years ago, so I don't remember the details. However, in our paper, we wrote that "The baseline, our method, and [37] run at 26, 24, and 96 FPS on a Titan RTX". So I think it can be run on real time.
 
However, the project is to perform 3D hand pose estimation, not gesture recognition. Further, it is trained on InterHand2.6M which has a dark background. So I think you need to perform hand segmentation first before feeding into the network.
